### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by ckald** [binspector/binspector#23]
Hi, I would like to inquire about the status and your plans on this project. 

 1. Is this still in development?
 1. How comprehensive the BFFT is for different binary file types? For example, simple home-baked binary formats used by scientists or more complex audio formats like WAV or even MP3
 1. Do you consider separating BFFT into a separate project aimed to provide the support of file formats parsing for diverse programming languages?

My motivation is the following. Already a couple of times I encountered a task of binary formats conversion. First, conversion of WAV samples into modified MilkyTracker's MOD format. And now - conversion between HDF files containing cosmological simulation data and handcrafted binary formats invented by the developers.

These kinds of tasks are repetitive as hell and I keep seeing definitions of the same structures in C, Fortran and Python code. I did some research on the topic, but could not find anything that I could use right away (please let me know, if you did). There should exist a descriptive format, that is simple enough for someone to write a parser implementation in any given language.

Your BFFT catches my eye because of being simple, C-like and potentially powerful enough to deal with the mentioned use cases. And it seems to me that separating BFFT parser into a library with interfaces for C/Fortran/Python should be relatively easy.

What do you think?

**Comment by fosterbrereton** [comment]
1. The project is still active and monitored, though no development is happening at present.
2. BFFT has been used to specify both simple formats (BMP) and complex ones (JPG, PSD.) For some file formats a fair amount of work is still required even after the file has been analyzed (e.g., reversing the huffman/DCT encoding of JPEG blocks.) Such post-processing is seen as outside the scope of Binspector/BFFT.
3. If you're looking to make bindings from the BFFT parser into other languages, I would be willing to talk through including them as part of the Binspector project.

**Comment by ckald** [comment]
I saw that you use boost and some Adobe dependencies. This is a quite big footprint. Can it be reduced? For language support it would be best to have a <1500 lines long parsers sourcefile that can be reimplemented in different languages. Or at least is should be a lightweight parser to compile with Python/Fortran bindings. Do you think this is possible?

**Comment by fosterbrereton** [comment]
The parser is pretty heavily dependent on the Adobe Source Libraries, which themselves depend on Boost. The C++ Standard has evolved quite a bit since ASL was first released, and it is very likely that many of those Boost dependencies can be eliminated in favor of Standard equivalents. While this would be a nontrivial amount of work, it should be doable.

The alternative, of course, would be to rewrite the lex and parser as a custom solution. While I'm not opposed to it (especially to gain bindings to other languages) it's not the kind of effort I have time for in the near term.

**Comment by ckald** [comment]
It would be enough to provide me the information on what type of parser is
required for BFFT. I am not particularly proficient in this part of CS, but
with little guidance I can figure it out

Op di 7 jul. 2015 19:32 schreef Foster Brereton <notifications@github.com>:

> The parser is pretty heavily dependent on the Adobe Source Libraries,
> which themselves depend on Boost. The C++ Standard has evolved quite a bit
> since ASL was first released, and it is very likely that many of those
> Boost dependencies can be eliminated in favor of Standard equivalents.
> While this would be a nontrivial amount of work, it should be doable.
>
> The alternative, of course, would be to rewrite the lex and parser as a
> custom solution. While I'm not opposed to it (especially to gain bindings
> to other languages) it's not the kind of effort I have time for in the near
> term.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/binspector/binspector/issues/23#issuecomment-119261608>
> .
>
-- 

Andrii Magalich
