### ISSUE TITLE
You might want to take a look at Kaitai Struct

### ISSUE THREAD

**Issue by KOLANICH** [binspector/binspector#28]
Hi. There is a tool called [Kaitai Struct](https://github.com/kaitai-io/kaitai_struct) which is similar to your one. We have an own YAML-based (in fact YAML is just a serialization) format for describing grammars and a library of ready-to-use formats and support generating code for multiple programming languages, and a WebIDE for real-time editing of the specs and getting the visualization. But we have no serialization support (the main long-term goal for now), no fuzzing, no other cool features we have a full bug tracker of requests of. There are multiple ways you can cooperate with us. I.e. implement support of our specs in your tool, or implement a convertor of your specs into ours one (I have a draft of a [convertor from Synalysis/Hexinator specs](https://github.com/KOLANICH/synalysis2kaitai) into ksy, it may be helpful to you if you want to implement a convertot from that format into your one, but strongly needs strong refactoring by adding a middleware and multiple passes, but its development has stalled).

**Comment by fosterbrereton** [comment]
Unfortunately I don't have the bandwidth to convert BFFTs to other formats at this time. If it's something you'd like to take on, I'm happy to consult.
