### ISSUE TITLE
Compilation fails with GCC

### ISSUE THREAD

**Issue by sur5r** [binspector/binspector#30]
While working on #29 I noticed that compilation with GCC is not possibly due to the way the endianness check is implemented.

GCC 10.2 reports the following error:

```
/usr/bin/c++ -DADOBE_STD_SERIALIZATION=1 -I/home/sur5r/git/binspector -I/home/sur5r/git/binspector/adobe_platform_libraries -I/home/sur5r/git/binspector/adobe_source_libraries -I/home/sur5r/git/binspector/boost -I/home/sur5r/git/binspector/stlab -I/home/sur5r/git/binspector/linenoise -Wall -Werror -std=c++17 -o CMakeFiles/binspector.dir/source/common.cpp.o -c /home/sur5r/git/binspector/source/common.cpp
In file included from /home/sur5r/git/binspector/source/common.cpp:24:
/home/sur5r/git/binspector/binspector/endian.hpp:38:29: error: ‘endian_k’ was not declared in this scope; did you mean ‘endian’?
   38 | constexpr bool endian_big_k{endian_k == endian::big};
      |                             ^~~~~~~~
      |                             endian
/home/sur5r/git/binspector/binspector/endian.hpp:39:32: error: ‘endian_k’ was not declared in this scope; did you mean ‘endian’?
   39 | constexpr bool endian_little_k{endian_k == endian::little};
      |                                ^~~~~~~~
      |                                endian

```

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60490 seems to indicate there is no simple fix that works on both compilers.

I'm opening this issue so others don't have to dig into this again.

**Comment by fosterbrereton** [comment]
Hopefully this is fixed with #31. Please let me know.

**Comment by sur5r** [comment]
Yes, this solved the endianness detection issue. I'm now facing an issue with some sse4.1 specific stuff in the updated boost lib.

**Comment by fosterbrereton** [comment]
@sur5r Glad the first problem is resolved. My guess about the second is due to how Boost is being compiled into the application. The `CMakeLists.txt` file doesn't do much around removing sources from the build that shouldn't be there, and you might be compiling a source file you don't need to.=

**Comment by sur5r** [comment]
Yes, deleting `boost/libs/atomic/src/find_address_sse41.cpp` makes it compile.

**Comment by fosterbrereton** [comment]
Ah, good. If you'd like please submit a PR with the necessary modifications to `CMakeLists.txt`.
